// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX3EOmuFdlMDWCd0Fh0-nBrRb8CdWpPAQ',
    appId: '1:608617952805:web:fa3a7667148e7c13d771cc',
    messagingSenderId: '608617952805',
    projectId: 'smartfinguide',
    authDomain: 'smartfinguide.firebaseapp.com',
    storageBucket: 'smartfinguide.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGXbCrSZ3nKDaP7mkUs0HggbV9I7DOzKY',
    appId: '1:608617952805:android:bc498f1a4d49e408d771cc',
    messagingSenderId: '608617952805',
    projectId: 'smartfinguide',
    storageBucket: 'smartfinguide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUOCxIwkAeh7_5tzZspF42oHPPLOE29o',
    appId: '1:608617952805:ios:61838a2c804ea7c0d771cc',
    messagingSenderId: '608617952805',
    projectId: 'smartfinguide',
    storageBucket: 'smartfinguide.appspot.com',
    iosBundleId: 'com.example.smartfinGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUOCxIwkAeh7_5tzZspF42oHPPLOE29o',
    appId: '1:608617952805:ios:61838a2c804ea7c0d771cc',
    messagingSenderId: '608617952805',
    projectId: 'smartfinguide',
    storageBucket: 'smartfinguide.appspot.com',
    iosBundleId: 'com.example.smartfinGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX3EOmuFdlMDWCd0Fh0-nBrRb8CdWpPAQ',
    appId: '1:608617952805:web:98d04a490efe66bcd771cc',
    messagingSenderId: '608617952805',
    projectId: 'smartfinguide',
    authDomain: 'smartfinguide.firebaseapp.com',
    storageBucket: 'smartfinguide.appspot.com',
  );
}
